### ISSUE TITLE
Port map for 2360 and 2960 style switches

### ISSUE THREAD

**Issue by garbled1** [slub/switchconfig#3]
I tried looking at the map files, but really couldn't wrap my head around the syntax for it, ie, what is important, and what is just table rows... maybe if you could describe it I could give it a shot..

The 2360 is 48 1G, + 4 10g + 1 10/100 MGMT.
The 2960 is 24 10/100 + 2 1G

**Comment by schorschii** [comment]
Can you please check out the current master branch? I added support for single (non-stacked) switches. Previously, only interface names like `Gi1/0/1` were detected in the port map. Now, interfaces like `Gi0/1` are detected too.

**Comment by schorschii** [comment]
@garbled1 Does the port map work with your switches with the current master branch?

**Comment by schorschii** [comment]
Closed due to inactivity.
